version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: augusto
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: gini_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
