"""Initial migration

Revision ID: 10684b712443
Revises: 
Create Date: 2024-08-29 11:29:51.060083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10684b712443'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gini_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('gini_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gini_index')
    # ### end Alembic commands ###
